### ISSUE TITLE
add `files` ts-node config

### ISSUE THREAD

**Issue by thiskevinwang** [thiskevinwang/express-kysely-zod#2]
Add this to `tsconfig.json::ts-node`

```jsonc
{
  "ts-node": {
    "files": true // enables `ts-node` to resolve local `.d.ts` files - https://stackoverflow.com/a/68295576
```

**Comment by Ninad-Patil** [comment]
hi, could you please check my pr

**Comment by thiskevinwang** [comment]
Hey @Ninad-Patil, thanks for your contribution! However this issue is stale and no longer applicable since moving this repository to a monorepo pattern:
- https://github.com/thiskevinwang/express-kysely-zod/commit/4daef553db27fd2bdc365e5e6b82c7a4fa24dff7#diff-75f36bcfc07eb004dd5015da827f52384b8a46ce57462fa0f50296a162123b00
